/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eschulz.pages;

import com.eschulz.data.Person;
import com.eschulz.data.XMLManager;
import java.util.ArrayList;

/**
 *
 * @author Eson
 */
public class PersonCreator extends javax.swing.JFrame {

    /**
     * Creates new form PersonCreator
     */
    public PersonCreator(ArrayList<Person> people) {
        this.people = people;
        isEditing = false;
        
        initComponents();
        this.setTitle("New Person");
        this.setVisible(true);
    }
    
    //Person creator for editing someone
    public PersonCreator(ArrayList<Person> people, Person p){
        this.people = people;
        this.person = p;
        isEditing = true;
        
        initComponents();
        
        this.firstTextField.setText(person.getFirstName());
        this.lastTextField.setText(person.getLastName());
        this.numberTextField.setText(person.getNumber());
        this.setTitle("Edit Person");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last name");

        jLabel3.setText("Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Ex: 507-333-4444");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errorLabel))
                            .addComponent(jLabel2)
                            .addComponent(lastTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(numberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(errorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String firstName = firstTextField.getText().trim();
        String lastName = lastTextField.getText().trim();
        String number = numberTextField.getText();
        
        if(firstName.isEmpty() || lastName.isEmpty() || number.isEmpty()){
            errorLabel.setText("Fill All Boxes");
        }
        else{
            if(! isEditing){
                //Checking to make sure the name isn't already in use
                for(Person p : people){
                    if(p.getFullName().equals(firstName + " " + lastName)){
                        errorLabel.setText("Name In Use");
                        return;
                    }
                }
            }
            
            //Cleaning up the number, if they use various different forms of writing it
            String newNumber = number.replace("-", "");
            newNumber = newNumber.replace(" ", "");
            if(newNumber.length() == 11){
                if(newNumber.charAt(0) == '1'){
                    newNumber = newNumber.substring(1, newNumber.length());
                }
                else{
                    errorLabel.setText("Not Valid Num");
                    return;
                }
            }
            else if(newNumber.length() != 10){
                errorLabel.setText("Not Valid Num");
                return;
            }
            else{
                try{
                    Long.valueOf(newNumber);
                }
                catch(NumberFormatException ex){
                    errorLabel.setText("Not Valid Num");
                    System.out.println(newNumber);
                    return;
                }
            }
            
            //Converted number
            newNumber = newNumber.substring(0, 3) + "-" + newNumber.substring(3, 6) + "-" + newNumber.substring(6,10);
           
            Person newPerson = new Person();
            newPerson.setFirstName(firstName);
            newPerson.setLastName(lastName);
            newPerson.setNumber(newNumber);
            if(isEditing){
                //Change the person in the xml file
                boolean worked = XMLManager.editPerson(newPerson, person);
                if(worked){
                    this.dispose();
                }
                else{
                    errorLabel.setText("Can't Write XML");
                }
            }
            else{
                boolean worked = XMLManager.writePerson(newPerson);
                if(worked){
                    this.dispose();
                }
                else{
                    errorLabel.setText("Can't Write XML");
                }
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private ArrayList<Person> people;
    private Person person;
    private boolean isEditing;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField firstTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lastTextField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
